### ISSUE TITLE
验证码result code:FAIL_UPNOTMATCH

### ISSUE THREAD

**Issue by hanwinbi** [leaplu/DailyCP#6]
您好，我在测试您的代码的时候发现反复登陆不了，检查发现字段needCaptcha为true，所以将您注释部分获取验证码的部分取消掉，手动输入验证码后 `result code`字段由原来的 `NOTMATCH` 变成了 `FAIL_UPNOTMATCH`
 因为本人对网络部分不是很熟悉，想请教以下怎么处理

**Comment by UzkiS** [comment]
刚刚同步了一下原作者的提交 你可以试试行不行，不行的话去原项目提交一下issue

**Comment by hanwinbi** [comment]
还是不行，我去原项目看看，谢谢
