### ISSUE TITLE
#使用action 报错了，但是我看不懂怎么办

### ISSUE THREAD

**Issue by nightmare-mio** [leaplu/DailyCP#7]
Error: Process completed with exit code 1.

**Comment by nightmare-mio** [comment]
![image](https://user-images.githubusercontent.com/52735303/118660053-6bae9580-b820-11eb-8ad5-9ef12c5c3a83.png)

**Comment by UzkiS** [comment]
连接错误 具体我没办法帮到你了

**Comment by UzkiS** [comment]
检查一下域名吧
